### ISSUE TITLE
TypeError: Cannot read properties of null (reading '$')     

### ISSUE THREAD

**Issue by emmetmink** [theoomoregbee/US-visa-appointment-notifier#31]
After it runs the script and logs in it gives this prompt  :
at login (D:\US-visa-appointment-notifier-main\index.js:17:28)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)     at async process (D:\US-visa-appointment-notifier-main\index.js:85:19)     at async D:\US-visa-appointment-notifier-main\index.js:103:5

**Comment by theoomoregbee** [comment]
This has been resolved - pull latest main branch

**Comment by hasancansaral** [comment]
@theoomoregbee I am still experiencing this issue as of now with the current latest main branch. Do you have any suggestions? Making the environment not prod resolves the issue, but running chrome headless breaks.

**Comment by gslopez** [comment]
plus 1 here, seeing same error
